apiVersion: v1
kind: ResourceQuota
metadata:
  name: resources-test-quota
  namespace: resources-test
spec:
  hard:
    requests.memory: 138Mi
    requests.cpu: 500m
    limits.memory: 256Mi
    limits.cpu: "1"
