apiVersion: v1
kind: Pod
metadata:
  name: resource-consumer-pod
spec:
  containers:
  - name: resource-consumer
    gcr.io/kubernetes-e2e-test-images/resource-consumer:1.5
  - name: busybox-sidecare
    image: radial/busyboxplus:curl
    command: ['sh', '-c', 'until curl localhost:8080/ConsumeCPU -d "millicores=100&durationSec=3600"; do sleep 5; done && while true; do sleep 10; done']
